import { type Metadata } from "next";
import { absoluteUrl, siteConfig } from "@/lib/site";

export async function generateMetadata(
  props: { params: Promise<{ tool: string; id: string }> }
): Promise<Metadata> {
  const params = await props.params;
  const decodedTool = decodeURIComponent(params.tool);
  const toolName = decodedTool.replace(/-/g, " ");

  return {
    title: `${toolName} Conversion Result`,
    description: `Access the ${toolName} conversion result generated by Convertz.`,
    alternates: {
      canonical: absoluteUrl(`/${params.tool}/${params.id}`),
    },
    openGraph: {
      title: `${toolName} Conversion Result | ${siteConfig.name}`,
      description: `Access your ${toolName} conversion result on ${siteConfig.name}.`,
      url: absoluteUrl(`/${params.tool}/${params.id}`),
      siteName: siteConfig.name,
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: `${toolName} Conversion Result | ${siteConfig.name}`,
      description: `Access your ${toolName} conversion result on ${siteConfig.name}.`,
    },
    robots: {
      index: false,
      follow: false,
      googleBot: {
        index: false,
        follow: false,
      },
    },
  };
}

export default function ConversionLayout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
